libreria/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from libros import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^libros/', include('libros.urls'), name="libros"),
    url(r'^$', views.index, name="index"),
    url(r'^usuarios/', include('usuarios.urls'), name="usuarios"),
]

libros/urls.py
from django.conf.urls import url
from . import views

app_name = "libros"

urlpatterns = [
    url(r'^$', views.dashboard, name="dashboard")
]

usuarios/urls.py
from django.conf.urls import url
from . import views

app_name = "usuarios"


urlpatterns = [
    url(r'logout/$', views.logout_user, name="logout" ),
    url(r'login/$', views.login_user, name="login"),
    url(r'crear_usuario/$', views.guardar_usuario, name="crear_usuario"),
]

libros/models/autor.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Autor(models.Model):
    nombre = models.CharField(max_length=100)

    class Meta:
        verbose_name = "Autor"
        verbose_name_plural = "Autores"
    
    def __unicode__(self):
        return self.nombre

libros/models/categoria.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Categoria(models.Model):
    nombre = models.CharField( max_length=50)

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"
    
    def __unicode__(self):
        return self.nombre

libros/models/libro.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from . import Autor
from . import Categoria

class Libro(models.Model):
    isbn = models.CharField(max_length=150)
    nombre = models.CharField( max_length=100)
    anio = models.CharField(max_length=4)
    numero_paginas = models.IntegerField()
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    disponible = models.BooleanField(default=True)

    class Meta():
        verbose_name = "Libro"
        verbose_name_plural = "Libros"
    
    def __unicode__(self):
        return self.nombre
    

libros/models/prestamo.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from . import Libro

class Prestamo(models.Model):
    ESTATUS = (
        ('a', 'Activo'),
        ('c', 'Cerrado')
    )

    libro = models.ForeignKey(Libro, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha_prestamo = models.DateField(auto_now=True)
    fecha_entrega = models.DateField(null=True, blank=True)
    estatus = models.CharField(max_length=8, choices=ESTATUS, default='a')

    class Meta:
        verbose_name = "Prestamo"
        verbose_name_plural = "Prestamos"

    
    def __unicode__(self):
        return "Nombre libro: {} Usuario: {} Estatus:".format(self.libro , self.usuario, self.estatus)

usuarios/models/perfil.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

class Perfil(models.Model):
    """Model definition for Perfil."""

    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    direccion = models.CharField(max_length=350)
    telefono = models.CharField(max_length=14)

    class Meta:
        """Meta definition for Perfil."""

        verbose_name = 'Perfil'
        verbose_name_plural = 'Perfiles'

    def __unicode__(self):
        """Unicode representation of Perfil."""
        return self.usuario.first_name

usuarios/forms.py
from django import forms
from django.contrib.auth.models import  User

from .models import Perfil

class LoginForm(forms.Form):
    username = forms.CharField(label='Username',max_length=60)
    password = forms.CharField(widget=forms.PasswordInput)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email', 'password',)

class UsuarioForm(forms.ModelForm):
    
    class Meta:
        model = Perfil
        fields = ('direccion', 'telefono')

libros/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse

def index(request):
    return render(request, 'index.html')

def dashboard(request):
    return render(request, "libreria/dashboard/index.html")

usuarios/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from .models import Perfil
from django.contrib.auth.models import User
from .models import Puesto
from decimal import Decimal


def login_user(request):
    if request.user.is_authenticated():
        return redirect("libros:dashboard")
    else:
        if request.method == "POST":
            username = request.POST.get('username', '')
            password = request.POST.get('password', '')

            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                print "si se logeo"
                return redirect("libros:dashboard")
            else:
                
                return render(request, 'usuarios/login.html')
        else:
            return render(request, 'usuarios/login.html')
            
def logout_user(request):
    logout(request)
    return redirect('/')

@login_required
def guardar_usuario(request):
    if request.method == "POST":
        try:
            username = request.POST.get('username')
            email = request.POST.get('email')
            password = request.POST.get('password')
            user = User.objects.create_user(username,email,password)
            user.first_name =  request.POST.get('first_name')
            user.email = request.POST.get('email')
            perfil = Perfil()
            perfil.direccion = request.POST.get('direccion')
            perfil.telefono = request.POST.get('telefono')
            user.save()                        
            perfil.usuario = user
            perfil.save()
            messages.success(request, 'Se creo el usuario correctamente')
            return redirect("libros:dashboard")
        except ValueError:
            datos = dict(request.POST)
            print datos
            context = {
                'datos': datos
            }
            messages.error(request, 'No se  guardo el usuario, por favor verifica los datos')
            return render(request, 'usuarios/crear_usuario.html', context)
        

    
    elif request.method == "GET":
        puestos = Puesto.objects.all()
        context = {
            'puestos': puestos,
        }
        return render(request, "usuarios/crear_usuario.html", context)

libros/templates/index.html
{% extends 'base/main.html' %}


{% block container %}
    <div class="row">
        <div class="col col-sm-12 col-md-12 col-lg-12">
            <h4>Libreria</h4>
        </div>
    </div>
{% endblock container %}
    

libros/templates/libreria/crear_prestamo.html
{% extends "base/main.html" %}


{% block container %}
    div.row>div.col.col-sm-12.
{% endblock container %}
    

libros/templates/libreria/dashboard/index.html
{% extends "base/main.html" %}


{% block container %}
    <div class="row">
        <div class="col col-sm-12 col-md-12 col-lg-12">
            {% if request.user.is_staff %}                
                <a href="" class="btn btn-primary">Crear prestamo</a>
            {% endif %}
            <a href="" class="btn btn-primary">Ver libros</a>
            <a href="" class="btn btn-primary">Ver prestamos</a>
            
        </div>
    </div>

        
{% endblock container %}
    

templates/base/main.html
{% load static %}
<!DOCTYPE html>
<!-- saved from url=(0059)http://getbootstrap.com/docs/4.0/examples/starter-template/ -->
<html lang="en">
  <head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Libreria</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'base/css/bootstrap.min.css'%}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'base/css/starter-template.css'%}" rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
        {% include "base/nav/_nav.html" %}
    </nav>

    <main role="main" class="container">

      <div class="starter-template">
        {% if messages %}
          {% for message in messages %}
              <div {% if message.tags == 'success' %} 
                class="alert alert-success"
              {% elif message.tags == "error" %}
                class="alert alert-danger"
              {% endif %}
              role="alert">{{ message }}</div>
          {% endfor %}
        {% endif %}
      
        {% block container %}
            
        {% endblock container %}
          
      </div>

    </main><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'base/js/jquery.min.js' %}"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src=" {% static 'base/js/popper.min.js' %}"></script>
    <script src="{% static 'base/js/bootstrap.min.js' %}"></script>
  

</body>
</html>

templates/base/nav/_nav.html
<a class="navbar-brand" href="{% url 'index' %}">Libreria</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarsExampleDefault">
  <ul class="navbar-nav mr-auto">
    {% if request.user.is_authenticated == False %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'usuarios:login' %}">Ingresar</a>
        </li>
    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'usuarios:logout' %}">Cerrar sesión</a>
        </li>
        
        {% if request.user.is_staff %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'usuarios:crear_usuario' %}">Crear usuario</a>
            </li>
        {% endif %}
    {% endif %}
    
  </ul>
</div>

usuarios/templates/usuarios/crear_usuario.html
{% extends 'base/main.html' %}


{% block container %}
    <div class="row">
        <div class="col col-sm-12 col-md-5 col-lg-5">              
            <h4>Registra un usuario</h4>
            <form action="{% url 'usuarios:crear_usuario' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" name="username" id="username" class="form-control" placeholder="Nombre de usaurio" required>
                </div>
                <div class="form-group">
                    <input type="password" name="password" id="password_id" class="form-control" placeholder="Contraseña" required>
                </div>
                <div class="form-group">
                    <input type="text" name="first_name" id="first_name_id" class="form-control" placeholder="Nombre">
                </div>
                <div class="form-group">
                    <input type="email" name="email" id="email_id" class="form-control" placeholder="Correo electronico">
                </div>
                <div class="form-group">
                    <input type="text" name="direccion" id="direccion_id" class="form-control" placeholder="Dirección">
                </div>
                <div class="form-group">
                    <input type="text" name="telefono" id="telefono_id" class="form-control" placeholder="Telefono">
                </div>

                <div class="form-group">
                    <input class="btn btn-primary" type="submit" value="Guardar">            
                </div>
            </form>
        </div>
    </div>
    
{% endblock container %}
    
    

usuarios/templates/usuarios/login.html
{% extends 'base/main.html' %}


{% block container %}
    <div class="row">
        <div class="col col-sm-12 col-md-4 col-lg-4">
            <form action="{% url 'usuarios:login' %}" method="POST">
                <h4>Iniciar sesión</h4>
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" name="username" class="form-control" placeholder="Nombre de usuario">            
                </div>
                <div class="form-group">
                    <input type="password" placeholder="Contraseña" name="password" class="form-control">
                </div>
                <div class="form-group">
                    <input class="btn btn-primary" type="submit" value="Entrar">            
                </div>  
            </form>
        </div>
    </div>
    
    
{% endblock container %}
    
    